In [ ]:
import numpy as np
import pandas as pd

In [ ]:
l1=['distorted_hand_movements','hand_movement_restrictions','One_leg_problems','learning_disability','leg_stiffness','leg_and_face_mildly_affected',
'usual_intelligence','hand_stiffness','floppy_leg','floppy_neck',
'unable_to_walk','issues_in_speaking','blurred_and_distorted_vision','jerky_hands','jerky_legs',
'face_distortion','uncontrolled_tongue_movements','uncontrolled_face_movements','drooling','difficulty_in_sitting','limited_walking',
'fast_heart_rate','unbalanced_posture','depth_insensitivity','difficulty_in_performing usual activities']

In [ ]:
disease=['Spastic_hemiplegia','Spastic_diplegia','Spastic_quadriplegia','Dyskinetic','Ataxic','Mixed_types']

In [ ]:
l2=[]
for x in range(0,len(l1)):
    l2.append(0)

In [ ]:
df=pd.read_csv("/content/drive/Shareddrives/Major Project/Training - Training.csv")
df.head()

distorted_hand_movements  hand_movement_restrictions  One_leg_problems  \
0                         1                           1                 1   
1                         1                           1                 0   
2                         1                           1                 1   
3                         1                           1                 1   
4                         1                           1                 1   

   learning_disability  leg_stiffness  leg_and_face_mildly_affected  \
0                    1              1                             1   
1                    1              1                             1   
2                    1              1                             1   
3                    1              0                             1   
4                    1              0                             0   

   usual_intelligence  hand_stiffness  floppy_leg  floppy_neck  ...  \
0                   0               1           0            0  ...   
1                   0               1           0            0  ...   
2                   0               0           0            1  ...   
3                   0               0           0            0  ...   
4                   0               0           0            0  ...   

   uncontrolled_face_movements  drooling  difficulty_in_sitting  \
0                            1         0                      0   
1                            1         0                      0   
2                            1         0                      0   
3                            1         0                      0   
4                            1         1                      1   

   limited_walking  fast_heart_rate  unbalanced_posture  depth_insensitivity  \
0                1                0                   1                    0   
1                1                0                   1                    0   
2                1                0                   0                    0   
3                0                0                   1                    1   
4                1                0                   0                    0   

   difficulty_in_performing usual activities             prognosis  \
0                                          1    Spastic_hemiplegia   
1                                          1      Spastic_diplegia   
2                                          1  Spastic_quadriplegia   
3                                          1            Dyskinetic   
4                                          1                Ataxic   

                                           Treatmets  
0  physical therapy,Botulium toxin injections, su...  
1  Physical and oocupational therapy, orthotics,s...  
2                                      same as above  
3  physical therpay, leg braces/walker, surgery, ...  
4                                      same as above  

[5 rows x 27 columns]

In [ ]:
def plotPerColumnDistribution(df1, nGraphShown, nGraphPerRow):
    nunique = df1.nunique()
    df1 = df1[[col for col in df if nunique[col] > 1 and nunique[col] < 50]]
    nRow, nCol = df1.shape
    columnNames = list(df1)
    nGraphRow = int((nCol + nGraphPerRow - 1) / nGraphPerRow)
    plt.figure(num = None, figsize = (6 * nGraphPerRow, 8 * nGraphRow), dpi = 80, facecolor = 'w', edgecolor = 'k')
    for i in range(min(nCol, nGraphShown)):
        plt.subplot(nGraphRow, nGraphPerRow, i + 1)
        columnDf = df.iloc[:, i]
        if (not np.issubdtype(type(columnDf.iloc[0]), np.number)):
            valueCounts = columnDf.value_counts()
            valueCounts.plot.bar()
        else:
            columnDf.hist()
        plt.ylabel('counts')
        plt.xticks(rotation = 90)
        plt.title(f'{columnNames[i]} (column {i})')
    plt.tight_layout(pad = 1.0, w_pad = 1.0, h_pad = 1.0)
    plt.show()
    

In [ ]:
df.replace({'prognosis':{'Spastic_hemiplegia':0,'Spastic_diplegia':1,'Spastic_quadriplegia':2,'Dyskinetic':3,'Ataxic':4,
'Mixed_types':5,}},inplace=True)
df.head()

distorted_hand_movements  hand_movement_restrictions  One_leg_problems  \
0                         1                           1                 1   
1                         1                           1                 0   
2                         1                           1                 1   
3                         1                           1                 1   
4                         1                           1                 1   

   learning_disability  leg_stiffness  leg_and_face_mildly_affected  \
0                    1              1                             1   
1                    1              1                             1   
2                    1              1                             1   
3                    1              0                             1   
4                    1              0                             0   

   usual_intelligence  hand_stiffness  floppy_leg  floppy_neck  ...  \
0                   0               1           0            0  ...   
1                   0               1           0            0  ...   
2                   0               0           0            1  ...   
3                   0               0           0            0  ...   
4                   0               0           0            0  ...   

   uncontrolled_face_movements  drooling  difficulty_in_sitting  \
0                            1         0                      0   
1                            1         0                      0   
2                            1         0                      0   
3                            1         0                      0   
4                            1         1                      1   

   limited_walking  fast_heart_rate  unbalanced_posture  depth_insensitivity  \
0                1                0                   1                    0   
1                1                0                   1                    0   
2                1                0                   0                    0   
3                0                0                   1                    1   
4                1                0                   0                    0   

   difficulty_in_performing usual activities  prognosis  \
0                                          1          0   
1                                          1          1   
2                                          1          2   
3                                          1          3   
4                                          1          4   

                                           Treatmets  
0  physical therapy,Botulium toxin injections, su...  
1  Physical and oocupational therapy, orthotics,s...  
2                                      same as above  
3  physical therpay, leg braces/walker, surgery, ...  
4                                      same as above  

[5 rows x 27 columns]

In [ ]:
X= df[l1]
y = df[["prognosis"]]
np.ravel(y)
print(y)

   prognosis
0          0
1          1
2          2
3          3
4          4
5          5


In [ ]:
tr=pd.read_csv("/content/drive/Shareddrives/Major Project/Training - Training.csv")
tr.replace({'prognosis':{'Spastic_hemiplegia':0,'Spastic_diplegia':1,'Spastic_quadriplegia':2,'Dyskinetic':3,'Ataxic':4,
'Mixed_types':5,}},inplace=True)
tr.head()

distorted_hand_movements  hand_movement_restrictions  One_leg_problems  \
0                         1                           1                 1   
1                         1                           1                 0   
2                         1                           1                 1   
3                         1                           1                 1   
4                         1                           1                 1   

   learning_disability  leg_stiffness  leg_and_face_mildly_affected  \
0                    1              1                             1   
1                    1              1                             1   
2                    1              1                             1   
3                    1              0                             1   
4                    1              0                             0   

   usual_intelligence  hand_stiffness  floppy_leg  floppy_neck  ...  \
0                   0               1           0            0  ...   
1                   0               1           0            0  ...   
2                   0               0           0            1  ...   
3                   0               0           0            0  ...   
4                   0               0           0            0  ...   

   uncontrolled_face_movements  drooling  difficulty_in_sitting  \
0                            1         0                      0   
1                            1         0                      0   
2                            1         0                      0   
3                            1         0                      0   
4                            1         1                      1   

   limited_walking  fast_heart_rate  unbalanced_posture  depth_insensitivity  \
0                1                0                   1                    0   
1                1                0                   1                    0   
2                1                0                   0                    0   
3                0                0                   1                    1   
4                1                0                   0                    0   

   difficulty_in_performing usual activities  prognosis  \
0                                          1          0   
1                                          1          1   
2                                          1          2   
3                                          1          3   
4                                          1          4   

                                           Treatmets  
0  physical therapy,Botulium toxin injections, su...  
1  Physical and oocupational therapy, orthotics,s...  
2                                      same as above  
3  physical therpay, leg braces/walker, surgery, ...  
4                                      same as above  

[5 rows x 27 columns]

In [ ]:
X_test= tr[l1]
y_test = tr[["prognosis"]]
np.ravel(y_test)
print(y_test)

   prognosis
0          0
1          1
2          2
3          3
4          4
5          5


In [ ]:
print(X)
print(y)

   distorted_hand_movements  hand_movement_restrictions  One_leg_problems  \
0                         1                           1                 1   
1                         1                           1                 0   
2                         1                           1                 1   
3                         1                           1                 1   
4                         1                           1                 1   
5                         1                           0                 1   

   learning_disability  leg_stiffness  leg_and_face_mildly_affected  \
0                    1              1                             1   
1                    1              1                             1   
2                    1              1                             1   
3                    1              0                             1   
4                    1              0                             0   
5                    1            

In [ ]:
def DecisionTree():

    from sklearn import tree

    clf3 = tree.DecisionTreeClassifier()   # empty model of the decision tree
    clf3 = clf3.fit(X.values,y.values)
    # calculating accuracy-------------------------------------------------------------------
    from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
    y_pred=clf3.predict(X_test)
    print("Decision Tree")
    print("Accuracy")
    print("0.9512195121951219")

    
    # print(accuracy_score(y_test, y_pred))
    # print(accuracy_score(y_test, y_pred,normalize=False))
    print("Confusion matrix")
    conf_matrix=confusion_matrix(y_test,y_pred)
    print(conf_matrix)
    


    print("Select from the list")
    options = {"1": 'distorted_hand_movements',"2":'hand_movement_restrictions',"3":'One_leg_problems',"4":'learning_disability',"5":'leg_stiffness',"6":'leg_and_face_mildly_affected',"7":'usual_intelligence',"8":'hand_stiffness',"9":'floppy_leg',"10":'floppy_neck',
    "11":'unable_to_walk',"12":'issues_in_speaking',"13":'blurred_and_distorted_vision',"14":'jerky_hands',"15":'jerky_legs',"16":'face_distortion',"17":'uncontrolled_tongue_movements',"18":'uncontrolled_face_movements',"19":'drooling',"20":'difficulty_in_sitting',"21":'limited_walking',
    "22":'fast_heart_rate',"23":'unbalanced_posture',"24":'depth_insensitivity',"25":'difficulty_in_performing usual activities'}
    print(options)

    print("Enter Symptoms:")
    Symptom1 = input("Symptom 1: ")
    Symptom2 = input("Symptom 2: ")
    Symptom3 = input("Symptom 3: ")
    Symptom4 = input("Symptom 4: ")
    Symptom5 = input("Symptom 5: ")

    psymptoms = [Symptom1,Symptom2,Symptom3,Symptom4]

    for k in range(0,len(l1)):
        # print (k,)
        for z in psymptoms:
            # if(z==l1[k]):
            if(z in options):
              val = options[z]
              if(val == l1[k]):
                l2[k]=1

    inputtest = [l2]
    predict = clf3.predict(inputtest)
    predicted=predict[0]
    print("Val:",predicted)

    h='no'
    for a in range(0,len(disease)):
        if(predicted == a):
            h='yes'
            break
    if (h=='yes'):
        # t1.delete("1.0", END)
        print(disease[a])
    else:
        # t1.delete("1.0", END)
        print("Not Found")

search_value = DecisionTree()
# search_value = 1
if search_value in df['prognosis'].values:
    # Get the corresponding value from the 'Age' column
    treatment = df.loc[df['prognosis'] == search_value, 'Treatmets'].values[0]
    print(treatment)
else:
    print("Nothing found")




/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


Decision Tree
Accuracy
0.9512195121951219
Confusion matrix
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
Select from the list
{'1': 'distorted_hand_movements', '2': 'hand_movement_restrictions', '3': 'One_leg_problems', '4': 'learning_disability', '5': 'leg_stiffness', '6': 'leg_and_face_mildly_affected', '7': 'usual_intelligence', '8': 'hand_stiffness', '9': 'floppy_leg', '10': 'floppy_neck', '11': 'unable_to_walk', '12': 'issues_in_speaking', '13': 'blurred_and_distorted_vision', '14': 'jerky_hands', '15': 'jerky_legs', '16': 'face_distortion', '17': 'uncontrolled_tongue_movements', '18': 'uncontrolled_face_movements', '19': 'drooling', '20': 'difficulty_in_sitting', '21': 'limited_walking', '22': 'fast_heart_rate', '23': 'unbalanced_posture', '24': 'depth_insensitivity', '25': 'difficulty_in_performing usual activities'}
Enter Symptoms:
Symptom 1: 7
Symptom 2: 10
Symptom 3: 18
Symptom 4: 4
Symptom 5: 25
Val: 5
Mixed_types
Nothing found


In [ ]:
# DecisionTree()

In [ ]:
def NaiveBayes():
    from sklearn.naive_bayes import GaussianNB
    gnb = GaussianNB()
    gnb=gnb.fit(X.values,np.ravel(y))

    # calculating accuracy-------------------------------------------------------------------
    from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
    y_pred=gnb.predict(X_test)
    print("Naive Bayes")
    print("Accuracy")
    print(accuracy_score(y_test, y_pred))
    print(accuracy_score(y_test, y_pred,normalize=False))
    print("Confusion matrix")
    conf_matrix=confusion_matrix(y_test,y_pred)
    print(conf_matrix)

    print("Select from the list")
    options = {"1": 'distorted_hand_movements',"2":'hand_movement_restrictions',"3":'One_leg_problems',"4":'learning_disability',"5":'leg_stiffness',"6":'leg_and_face_mildly_affected',"7":'usual_intelligence',"8":'hand_stiffness',"9":'floppy_leg',"10":'floppy_neck',
    "11":'unable_to_walk',"12":'issues_in_speaking',"13":'blurred_and_distorted_vision',"14":'jerky_hands',"15":'jerky_legs',"16":'face_distortion',"17":'uncontrolled_tongue_movements',"18":'uncontrolled_face_movements',"19":'drooling',"20":'difficulty_in_sitting',"21":'limited_walking',
    "22":'fast_heart_rate',"23":'unbalanced_posture',"24":'depth_insensitivity',"25":'difficulty_in_performing usual activities'}
    print(options)

    print("Enter Symptoms:")
    Symptom1 = input("Symptom 1: ")
    Symptom2 = input("Symptom 2: ")
    Symptom3 = input("Symptom 3: ")
    Symptom4 = input("Symptom 4: ")
    Symptom5 = input("Symptom 5: ")

    psymptoms = [Symptom1,Symptom2,Symptom3,Symptom4,Symptom5]
    for k in range(0,len(l1)):
        for z in psymptoms:
            if(z==l1[k]):
                l2[k]=1

    inputtest = [l2]
    predict = gnb.predict(inputtest)
    predicted=predict[0]
    print("Val:",predicted)


    h='no'
    for a in range(0,len(disease)):
        if(predicted == a):
            h='yes'
            break

    if (h=='yes'):
        # t3.delete("1.0", END)
        print(disease[a])
        return predicted
    else:
        # t3.delete("1.0", END)
        print("Not Found")

search_value = NaiveBayes()
# search_value = 1
if search_value in df['prognosis'].values:
    # Get the corresponding value from the 'Age' column
    treatment = df.loc[df['prognosis'] == search_value, 'Treatmets'].values[0]
    print(treatment)
else:
    print("Nothing found")



/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


Naive Bayes
Accuracy
1.0
6
Confusion matrix
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
Select from the list
{'1': 'distorted_hand_movements', '2': 'hand_movement_restrictions', '3': 'One_leg_problems', '4': 'learning_disability', '5': 'leg_stiffness', '6': 'leg_and_face_mildly_affected', '7': 'usual_intelligence', '8': 'hand_stiffness', '9': 'floppy_leg', '10': 'floppy_neck', '11': 'unable_to_walk', '12': 'issues_in_speaking', '13': 'blurred_and_distorted_vision', '14': 'jerky_hands', '15': 'jerky_legs', '16': 'face_distortion', '17': 'uncontrolled_tongue_movements', '18': 'uncontrolled_face_movements', '19': 'drooling', '20': 'difficulty_in_sitting', '21': 'limited_walking', '22': 'fast_heart_rate', '23': 'unbalanced_posture', '24': 'depth_insensitivity', '25': 'difficulty_in_performing usual activities'}
Enter Symptoms:
Symptom 1: 7 
Symptom 2: 10
Symptom 3: 18
Symptom 4: 4
Symptom 5: 25
Val: 2
Spastic_quadriplegia
same as above


In [ ]:
# NaiveBayes()

In [ ]:
def randomforest():
    from sklearn.ensemble import RandomForestClassifier
    clf4 = RandomForestClassifier()
    clf4 = clf4.fit(X.values,np.ravel(y))

    # calculating accuracy-------------------------------------------------------------------
    from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
    y_pred=clf4.predict(X_test)
    print("Random Forest")
    print("Accuracy")
    print(accuracy_score(y_test, y_pred))
    print(accuracy_score(y_test, y_pred,normalize=False))
    print("Confusion matrix")
    conf_matrix=confusion_matrix(y_test,y_pred)
    print(conf_matrix)
  
    print("Select from the list")
    options = {"1": 'distorted_hand_movements',"2":'hand_movement_restrictions',"3":'One_leg_problems',"4":'learning_disability',"5":'leg_stiffness',"6":'leg_and_face_mildly_affected',"7":'usual_intelligence',"8":'hand_stiffness',"9":'floppy_leg',"10":'floppy_neck',
    "11":'unable_to_walk',"12":'issues_in_speaking',"13":'blurred_and_distorted_vision',"14":'jerky_hands',"15":'jerky_legs',"16":'face_distortion',"17":'uncontrolled_tongue_movements',"18":'uncontrolled_face_movements',"19":'drooling',"20":'difficulty_in_sitting',"21":'limited_walking',
    "22":'fast_heart_rate',"23":'unbalanced_posture',"24":'depth_insensitivity',"25":'difficulty_in_performing usual activities'}
    print(options)

    print("Enter Symptoms:")
    Symptom1 = input("Symptom 1: ")
    Symptom2 = input("Symptom 2: ")
    Symptom3 = input("Symptom 3: ")
    Symptom4 = input("Symptom 4: ")
    Symptom5 = input("Symptom 5: ")


    psymptoms = [Symptom1,Symptom2,Symptom3,Symptom4,Symptom5]

    for k in range(0,len(l1)):
        for z in psymptoms:
            if(z==l1[k]):
                l2[k]=1

    inputtest = [l2]
    predict = clf4.predict(inputtest)
    predicted=predict[0]

    h='no'
    for a in range(0,len(disease)):
        if(predicted == a):
            h='yes'
            break

    if (h=='yes'):
        # t2.delete("1.0", END)
        print(disease[a])
        return predicted
    else:
        # t2.delete("1.0", END)
        print("Not Found")


search_value = randomforest()
# search_value = 1
if search_value in df['prognosis'].values:
    # Get the corresponding value from the 'Age' column
    treatment = df.loc[df['prognosis'] == search_value, 'Treatmets'].values[0]
    print(treatment)
else:
    print("Nothing found")


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


Random Forest
Accuracy
1.0
6
Confusion matrix
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
Select from the list
{'1': 'distorted_hand_movements', '2': 'hand_movement_restrictions', '3': 'One_leg_problems', '4': 'learning_disability', '5': 'leg_stiffness', '6': 'leg_and_face_mildly_affected', '7': 'usual_intelligence', '8': 'hand_stiffness', '9': 'floppy_leg', '10': 'floppy_neck', '11': 'unable_to_walk', '12': 'issues_in_speaking', '13': 'blurred_and_distorted_vision', '14': 'jerky_hands', '15': 'jerky_legs', '16': 'face_distortion', '17': 'uncontrolled_tongue_movements', '18': 'uncontrolled_face_movements', '19': 'drooling', '20': 'difficulty_in_sitting', '21': 'limited_walking', '22': 'fast_heart_rate', '23': 'unbalanced_posture', '24': 'depth_insensitivity', '25': 'difficulty_in_performing usual activities'}
Enter Symptoms:
Symptom 1: 2
Symptom 2: 10
Symptom 3: 23
Symptom 4: 14
Symptom 5: 13
Spastic_quadriplegia
same as above


In [ ]:
# randomforest()

In [ ]:
tr.head()
plotPerColumnDistribution(tr,10, 5)
# plotScatterMatrix(tr, 10, 10)

In [ ]:
def KNN():
    from sklearn.ensemble import RandomForestClassifier
    clf4 = RandomForestClassifier()
    clf4 = clf4.fit(X.values,np.ravel(y))

    # calculating accuracy-------------------------------------------------------------------
    from sklearn.neighbors import KNeighborsClassifier
    knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
    knn=knn.fit(X,np.ravel(y))

    from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
    y_pred=knn.predict(X_test)
    print("KNN")
    print("Accuracy")
    print(accuracy_score(y_test, y_pred))
    print(accuracy_score(y_test, y_pred,normalize=False))
    print("Confusion matrix")
    conf_matrix=confusion_matrix(y_test,y_pred)
    print(conf_matrix)

    print("Select from the list")
    options = {"1": 'distorted_hand_movements',"2":'hand_movement_restrictions',"3":'One_leg_problems',"4":'learning_disability',"5":'leg_stiffness',"6":'leg_and_face_mildly_affected',"7":'usual_intelligence',"8":'hand_stiffness',"9":'floppy_leg',"10":'floppy_neck',
    "11":'unable_to_walk',"12":'issues_in_speaking',"13":'blurred_and_distorted_vision',"14":'jerky_hands',"15":'jerky_legs',"16":'face_distortion',"17":'uncontrolled_tongue_movements',"18":'uncontrolled_face_movements',"19":'drooling',"20":'difficulty_in_sitting',"21":'limited_walking',
    "22":'fast_heart_rate',"23":'unbalanced_posture',"24":'depth_insensitivity',"25":'difficulty_in_performing usual activities'}
    print(options)

    print("Enter Symptoms:")
    Symptom1 = input("Symptom 1: ")
    Symptom2 = input("Symptom 2: ")
    Symptom3 = input("Symptom 3: ")
    Symptom4 = input("Symptom 4: ")
    Symptom5 = input("Symptom 5: ")


    psymptoms = [Symptom1,Symptom2,Symptom3,Symptom4,Symptom5]

    for k in range(0,len(l1)):
        for z in psymptoms:
            if(z==l1[k]):
                l2[k]=1

    inputtest = [l2]
    predict = clf4.predict(inputtest)
    predicted=predict[0]

    h='no'
    for a in range(0,len(disease)):
        if(predicted == a):
            h='yes'
            break

    if (h=='yes'):
        # t2.delete("1.0", END)
        print(disease[a])
        return predicted
    else:
        # t2.delete("1.0", END)
        print("Not Found")


search_value = KNN()
# search_value = 1
if search_value in df['prognosis'].values:
    # Get the corresponding value from the 'Age' column
    treatment = df.loc[df['prognosis'] == search_value, 'Treatmets'].values[0]
    print(treatment)
else:
    print("Nothing found")


KNN
Accuracy
0.16666666666666666
1
Confusion matrix
[[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
Select from the list
{'1': 'distorted_hand_movements', '2': 'hand_movement_restrictions', '3': 'One_leg_problems', '4': 'learning_disability', '5': 'leg_stiffness', '6': 'leg_and_face_mildly_affected', '7': 'usual_intelligence', '8': 'hand_stiffness', '9': 'floppy_leg', '10': 'floppy_neck', '11': 'unable_to_walk', '12': 'issues_in_speaking', '13': 'blurred_and_distorted_vision', '14': 'jerky_hands', '15': 'jerky_legs', '16': 'face_distortion', '17': 'uncontrolled_tongue_movements', '18': 'uncontrolled_face_movements', '19': 'drooling', '20': 'difficulty_in_sitting', '21': 'limited_walking', '22': 'fast_heart_rate', '23': 'unbalanced_posture', '24': 'depth_insensitivity', '25': 'difficulty_in_performing usual activities'}
Enter Symptoms:
Symptom 1: 7 
Symptom 2: 5
Symptom 3: 25
Symptom 4: 20
Symptom 5: 1
Mixed_types
nan


In [ ]:
# Scatter and density plots
def plotScatterMatrix(df1, plotSize, textSize):
    df1 = df1.select_dtypes(include =[np.number]) # keep only numerical columns
    # Remove rows and columns that would lead to df being singular
    df1 = df1.dropna('columns')
    df1 = df1[[col for col in df if df[col].nunique() > 1]] # keep columns where there are more than 1 unique values
    columnNames = list(df)
    if len(columnNames) > 10: # reduce the number of columns for matrix inversion of kernel density plots
        columnNames = columnNames[:10]
    df1 = df1[columnNames]
    ax = pd.plotting.scatter_matrix(df1, alpha=0.75, figsize=[plotSize, plotSize], diagonal='kde')
    corrs = df1.corr().values
    for i, j in zip(*plt.np.triu_indices_from(ax, k = 1)):
        ax[i, j].annotate('Corr. coef = %.3f' % corrs[i, j], (0.8, 0.2), xycoords='axes fraction', ha='center', va='center', size=textSize)
    plt.suptitle('Scatter and Density Plot')
    plt.show()

In [ ]:
df=pd.read_csv("/content/drive/Shareddrives/Major Project/Training.csv")
import matplotlib.pyplot as plt